
name: Hello PowerShell

on: 
  push:
    branches:
      - main
jobs:
  hello-job:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PowerShell script
        run: ./hello.ps1
        shell: pwsh
#Just commenting this line to test the workflow
        # This is a comment in the YAML file
        # The script will print "Hello, World!" to the console