
name: Hello PowerShell

on: 
  push:
    branches:
      - main
jobs:
  hello-job:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PowerShell script
        run: ./hello.ps1
        shell: pwsh
